- name: Install Nginx
  ansible.builtin.dnf:
    name: nginx
    state: installed

- name: Copy Expense Configuration File
  ansible.builtin.template:
    src: expense.conf
    dest: /etc/nginx/default.d/expense.conf

- name: App Pre-Requisites
  ansible.builtin.include_role:
    name: common
    tasks_from: app_prereq

- name: Start Nginx Service
  ansible.builtin.systemd_service:
    name: nginx
    enabled: true
    state: restarted

- name: NewRelic Setup for Nginx
  ansible.builtin.shell: curl -Ls https://download.newrelic.com/install/newrelic-cli/scripts/install.sh | bash &&  NEW_RELIC_API_KEY={{ lookup('amazon.aws.aws_ssm', 'expense.newrelic.key', region='us-east-1' ) }} NEW_RELIC_ACCOUNT_ID={{ lookup('amazon.aws.aws_ssm', 'expense.newrelic.key', region='us-east-1' ) }} /usr/local/bin/newrelic install -y



