format_version: 10
pipelines:
  mysql:
    group: defaultGroup
    label_template: "${COUNT}"
    lock_behavior: none
    display_order: -1
    materials:
      ansible:
        git: https://github.com/raghudevopsb77/expense-ansible
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
    - DEV:
        fetch_materials: true
        approval:
          type: manual
        jobs:
          deployment:
            timeout: 0
            tasks:
            - exec:
                command: ansible-playbook
                arguments: ["-i", "frontend-dev.rdevopsb73.online,", "-e", "ansible_user=centos", "-e", "ansible_password=DevOps321", "expense.yml", "-e", "service_name=mysql", "-e", "env=dev"]


    - QA:
        fetch_materials: true
        approval:
          type: manual
          allow_only_on_success: true
        jobs:
          deployment:
            timeout: 0
            tasks:
            - exec:
                command: ls
                arguments:
                  - -l
                  - -A


    - UAT:
        fetch_materials: true
        approval:
          type: manual
          allow_only_on_success: true
        jobs:
          deployment:
            timeout: 0
            tasks:
            - exec:
                command: ls
                arguments:
                  - -l
                  - -A

    - PROD:
        fetch_materials: true
        approval:
          type: manual
          allow_only_on_success: true
        jobs:
          deployment:
            timeout: 0
            tasks:
            - exec:
                command: ls
                arguments:
                  - -l
                  - -A